### ISSUE TITLE
Could you please explain using a factor of *4 in each of your preset processing algorithms?

### ISSUE THREAD

**Issue by ballantynedewolf** [jayankaghosh/chobi#1]
Hi, I'm extending Chobi to perform a red-free desaturation algorithm on ocular fundus photos. This is a diagnostic technique to eg distinguish melanin from blood. I thought I would add another preset or two and I'm trying to work out why you use that line index=(y*4)*imageWidth+(x*4) in getColorAt and setColorAt?
Anyway, your app is perfect for my purpose - I just don't need the complexity of JIMP or CamanJS for this.

**Comment by jayankaghosh** [comment]
@ballantynedewolf It's great that you've found this app useful! To be honest it's been a while since I've gone through the source code of Chobi and I've forgotten most aspects of it. If you're willing I could sit with it when I'm free and try to remember why I wrote that specific line.

Just to clarify, is it not behaving as expected? Or are you curious to know why it's implemented in that way?

**Comment by ballantynedewolf** [comment]
Just curious. Fundus images are usually vignetted, so I may speed it up by not processing the pixels in the vignette. Hence it is useful to know exactly how the getImageData(x,y) methods work.

**Comment by jayankaghosh** [comment]
I think it has something to do with the fact that the `getImageData` function of canvas returns the array with R, G, B, and A values

**Comment by ballantynedewolf** [comment]
Right, so each pixel has 4 indeces?

**Comment by jayankaghosh** [comment]
Yes. if you `console.log(obj.imageData.data)` you'll see a huge array of numbers. Each set of 4 numbers represent one pixel. They are the R, G, B, and A values

**Comment by jayankaghosh** [comment]
Hoping that this resolves your question. I am closing the issue. Feel free to open it back if you need further clarification.

P.S Would love to know more about your finished product once it's done. Share a demo link maybe? :)

**Comment by ballantynedewolf** [comment]
Here is my *prototype app
<https://s3-ap-southeast-2.amazonaws.com/wolfchart.org/redFree/index.html>
*based
off your demo webpage. I have a number of colleagues testing it, and if
they are satisfied, I will make a proper nice looking app with a good UX,
maybe a PWA.
I appreciate any suggestion from you, and thanks again for building the
perfect script for my purposes.
I attach a couple of images that show the diagnostic purpose. In the first
pair you will see the dark lesion at the bottom disappears in the red free
process, proving it to be melanin and probably in the choroid of the eye.
In the second pair, the red free process makes the two splinter
haemorrhages around the optic nerve appear black, proving that they are
blood.
Jonathan


  @@-?
( -
the fashion and sober design
will make you special

**Comment by jayankaghosh** [comment]
Hey. Went through the app. Looks dope! Yeah making a react based SPA for example would make it even better.

Also, I didn't get images you shared. Let's move this conversation over Email. Drop me an email at jayankaghosh@gmail.com. And let's chat :)
